language: go

go:
  - 1.11
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
notifications:
  email:
    on_success: never
after_success:
  - bash <(curl -s https://codecov.io/bash)
